#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

N="${1:-15}"
SCHEME="${2:-star}"
OUT="${3:-$ROOT_DIR/docker-compose.yml}"

if [ "$N" -lt 2 ]; then
    echo "[gen] N must be >= 2, got $N" >&2
    exit 1
fi

case "$SCHEME" in
    star|ring|tree|multiseed) ;;
    *) echo "[gen] unknown scheme: $SCHEME (star|ring|tree|multiseed)" >&2; exit 1 ;;
esac

BASE_PORT=9001
PROJECT="p2pnode"
NETWORK="p2pnet"
IMAGE="p2pnode:latest"
UID_GID="$(id -u):$(id -g)"

echo "[gen] N=$N scheme=$SCHEME output=$OUT user=$UID_GID"

{
    echo "# AUTO-GENERATED by scripts/docker_gen_compose.sh"
    echo "# N=$N scheme=$SCHEME"
    echo "# Do not edit manually."
    echo
    echo "name: $PROJECT"
    echo
    echo "services:"

    for i in $(seq 1 "$N"); do
        idx=$(printf '%02d' "$i")
        port=$((BASE_PORT + i - 1))
        svc="node-$idx"
        host="$svc"

        case "$SCHEME" in
            star)
                if [ "$i" -eq 1 ]; then BOOT=""; else BOOT="node-01:9001"; fi
                ;;
            ring)
                if [ "$i" -eq 1 ]; then BOOT=""; else
                    prev=$(printf '%02d' $((i - 1)))
                    BOOT="node-$prev:$((BASE_PORT + i - 2))"
                fi
                ;;
            tree)
                if [ "$i" -eq 1 ]; then BOOT=""; else
                    parent=$((i / 2))
                    pp=$(printf '%02d' "$parent")
                    BOOT="node-$pp:$((BASE_PORT + parent - 1))"
                fi
                ;;
            multiseed)
                if [ "$i" -le 3 ]; then BOOT=""; else
                    BOOT="node-01:9001,node-02:9002,node-03:9003"
                fi
                ;;
        esac

        DEPS=""
        case "$SCHEME" in
            star)
                if [ "$i" -gt 1 ]; then
                    DEPS="      - node-01"
                fi
                ;;
            ring)
                if [ "$i" -gt 1 ]; then
                    prev=$(printf '%02d' $((i - 1)))
                    DEPS="      - node-$prev"
                fi
                ;;
            tree)
                if [ "$i" -gt 1 ]; then
                    parent=$((i / 2))
                    pp=$(printf '%02d' "$parent")
                    DEPS="      - node-$pp"
                fi
                ;;
            multiseed)
                if [ "$i" -gt 3 ]; then
                    for dep in 1 2 3; do
                        if [ "$dep" -ne "$i" ]; then
                            if [ -n "$DEPS" ]; then
                                DEPS="${DEPS}"$'\n'"      - node-$(printf '%02d' "$dep")"
                            else
                                DEPS="      - node-$(printf '%02d' "$dep")"
                            fi
                        fi
                    done
                fi
                ;;
        esac

        echo "  $svc:"
        echo "    image: $IMAGE"
        echo "    container_name: ${PROJECT}-${svc}"
        echo "    hostname: $host"
        echo "    user: \"$UID_GID\""
        echo "    networks: [$NETWORK]"
        echo "    ports:"
        echo "      - \"$port:$port\""
        echo "    environment:"
        echo "      NODE_STATE_DIR: /state"
        echo "      LISTEN_HOST: \"0.0.0.0\""
        echo "      ADVERTISE_HOST: $host"
        echo "      LISTEN_PORT: \"$port\""
        echo "      EXPORT_DIR: /metrics"
        echo "      EXPORT_INTERVAL_MS: \"2000\""
        echo "      LOG_LEVEL: \"INFO\""
        echo "      K_BUCKET_SIZE: \"4\""
        echo "      ALPHA: \"3\""
        if [ "$i" -eq 1 ]; then
            echo "      PUBLISH_SELF: \"true\""
            echo "      PUBLISH_WAIT_MS: \"15000\""
        fi
        if [ -n "$BOOT" ]; then
            echo "      BOOTSTRAP_PEERS: \"$BOOT\""
        fi
        echo "    volumes:"
        echo "      - ./state-docker/$svc:/state"
        echo "      - ./logs-docker/$svc:/logs"
        echo "      - ./metrics-docker/$svc:/metrics"
        echo "    restart: unless-stopped"
        if [ -n "$DEPS" ]; then
            echo "    depends_on:"
            echo "$DEPS"
        fi
        echo
    done

    echo "networks:"
    echo "  $NETWORK:"
    echo "    driver: bridge"
    echo "    name: ${PROJECT}_${NETWORK}"
} > "$OUT"

echo "[gen] wrote $OUT ($(wc -l < "$OUT") lines)"
